### ISSUE TITLE
adding custom repos until we have a mirror

### ISSUE THREAD

**Issue by ghost** [Miouyouyou/armbian-desktop#1]
we need a way to add a repo file if a custom ppa is required to build the desktop like with dde we do not currently mirror the pkgs so .  so is there a way to have a repo file in the desktop dir used for adding custom repos ?

**Comment by Miouyouyou** [comment]
Not for the moment.

This could be done easily, however, by just copying any repo file available in the generated image /etc/apt/sources.list.d , or aggregate them and write only one file.

I'll try to add this feature this week. This should not be too hard.

**Comment by Miouyouyou** [comment]
Ok, after thinking about it, since we also need the GPG keys for the PPA repos, adding a "ppa" sub-directory in every category, with files containing PPA addresses, and then execute commands to add them to the system before installing the desktop softwares, might work better.

I'll try to add this today and test this.

**Comment by Miouyouyou** [comment]
The functionality has been added, but still need to be documented. I'm closing this one and adding a note to the documentation bug report.
