### ISSUE TITLE
custom install flags

### ISSUE THREAD

**Issue by ghost** [Miouyouyou/armbian-desktop#2]
we need a way to set 2 optional flags when building desktops --install-reccomends and --install-suggests like a file called install_flags .thete is also --noinstall for both of these also. 

this would allow for build desktops to include more when needed.

**Comment by Miouyouyou** [comment]
Are the apt options actually named "--install-recommends" and "--install-suggests" ? I don't have a Debian system available right now, so I can't really check.

If that's the case, a simple menu with selectable flags, like :

* [x] recommends Install recommended packages
* [x] suggests install suggested packages

Should generate a list like INSTALL_FLAGS="recommends suggests"

Then, it's just basically a matter of doing something like :

```bash
for flag in INSTALL_FLAGS; do
  apt_additional_flags+=" --install-${flag}"
done
```

**Comment by RichNeese** [comment]
so thhen now how to set this  ? for testing sorry a little lost

**Comment by ghost** [comment]
so your saying like this ./compile.sh CLEAN_LEVEL="" INSTALL_FLAGS="recommends suggests" BOARD=pinebook-pro BRANCH=current RELEASE=focal BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_ONLY=no KERNEL_CONFIGURE=no DESKTOP_ENVIRONMENT="budgie" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_full" COMPRESS_OUTPUTIMAGE=sha,gpg,img,xz

**Comment by RichNeese** [comment]
when you have time I need help getting the custom/board/pinebook-pro patches in to this ..
https://github.com/armbian/build/pull/2208/files

**Comment by Miouyouyou** [comment]
Once I add the feature, yes. It's not added for the moment.

**Comment by Miouyouyou** [comment]
This has been added here : https://github.com/Miouyouyou/armbian-desktop/commit/195cce185cd5ca4b5966d1bab258fe09a967f1b0

The environment variable `DESKTOP_APT_FLAGS_SELECTED` and can be defined like this :
`DESKTOP_APT_FLAGS_SELECTED="suggests"`

Through I HIGHLY recommend to NOT use that option, unless you're absolutely sure you want it. This generates gigantic build over small packages installations, since the flag will recursively propagate on each dependency of every package you're trying to install.
